# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-29 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190326_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Upload',
            new_name='upload',
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default='username', max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default='username', max_length=30),
        ),
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='traditional',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
