# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-01 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190329_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_username',
            field=models.CharField(default='employee username', max_length=30),
        ),
    ]
